assetmanager: Add ability to filter asset listing based on category
LinkopingsStudentspex/internsidor pull request #50
Opened 2022-12-22 04:06 UTC by Rovanion

2022-12-26 14:17 UTC, Karlinde requested changes
Assetmanager-appen använder djangos translation-system och dessa ändringar borde kanske använda samma system för att inte blanda stilar. Oavsett så borde URL-parametern för kategori vara på engelska precis som övriga delarna av URL:en.

2022-12-26 15:53 UTC, Rovanion commented
Efter en viss måtta huvudbankande så tror jag att jag lyckats med översättningsdansen.

2023-06-18 10:33 UTC, Karlinde approved these changes

2023-06-18 12:28 UTC, merged

2023-06-27 09:27 UTC, Rovanion commented
@anargam Vet du hur du produktionssätter en ny version av internsidorna? För jag tror inte de här ändringarna är live än.

2023-07-02 11:15 UTC, anargam commented
Sorry, tjänsten omstartad.

On Tue, 27 Jun 2023 at 11:28, Rovanion Luckey ***@***.***>
wrote:

> @anargam <https://github.com/anargam> Vet du hur du produktionssätter en
> ny version av internsidorna? För jag tror inte de här ändringarna är live
> än.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LinkopingsStudentspex/internsidor/pull/50#issuecomment-1609128215>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABHAECDGJEH5CBNWRG2LKULXNKRSJANCNFSM6AAAAAATGJFXHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>